use gitwho::config::Config;
use gitwho::sync;

const ACCOUNTS: &str = r#"
    [defaults]
    account = "Personal"
    gitName = "Daniel Carmingham"

    [[accounts]]
    name = "Personal"
    provider = "github"
    email = "me@example.com"
    gitCredential = "GH_TOKEN"
    sshKey = "~/.ssh/id_ed25519_personal"
    match = ["github.com/Personal/**"]
    paths = ["/Users/daniel/Developer/DanielCarmingham/"]

    [[accounts]]
    name = "Work"
    provider = "github"
    email = "me@work.example"
    gitCredential = "GH_TOKEN"
    match = ["github.com/WorkOrg/**"]
"#;

fn generate() -> sync::Plan {
    let config = Config::parse(ACCOUNTS).unwrap();
    sync::plan(&config, std::path::Path::new("/home/x/.config/gitwho/git"))
}

fn file<'a>(plan: &'a sync::Plan, name: &str) -> &'a str {
    plan.files
        .iter()
        .find(|f| f.path.file_name().unwrap() == name)
        .map(|f| f.contents.as_str())
        .unwrap_or_else(|| panic!("no generated file named {name}"))
}

#[test]
fn each_account_gets_an_identity_file() {
    let plan = generate();
    let personal = file(&plan, "Personal.gitconfig");

    assert!(personal.contains("email = me@example.com"));
    assert!(personal.contains("name = Daniel Carmingham"));
}

#[test]
fn an_account_with_an_ssh_key_pins_it_and_one_without_does_not() {
    let plan = generate();

    assert!(
        file(&plan, "Personal.gitconfig").contains("sshcommand"),
        "an account declaring a key should pin it"
    );
    assert!(
        !file(&plan, "Work.gitconfig").contains("sshcommand"),
        "an account with no key must not inherit someone else's"
    );
}

/// `hasconfig:remote.*.url:` matches the literal remote string, so one account
/// pattern has to become every URL spelling of it -- otherwise an ssh clone of
/// a matched org silently misses.
#[test]
fn a_pattern_becomes_every_url_form_git_might_see() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    for expected in [
        "hasconfig:remote.*.url:https://github.com/Personal/**",
        "hasconfig:remote.*.url:*@github.com:Personal/**",
        "hasconfig:remote.*.url:ssh://*@github.com/Personal/**",
    ] {
        assert!(
            includes.contains(expected),
            "missing URL form {expected}; got:\n{includes}"
        );
    }
}

#[test]
fn declared_paths_become_gitdir_rules_for_repos_with_no_remote() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    assert!(
        includes.contains("gitdir:/Users/daniel/Developer/DanielCarmingham/"),
        "a declared path should produce a gitdir rule; got:\n{includes}"
    );
}

/// URL rules must come after path rules: last include wins in git, and the
/// remote is the better evidence.
#[test]
fn url_rules_are_applied_after_path_rules() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    let first_path = includes.find("gitdir:").expect("expected a gitdir rule");
    let first_url = includes
        .find("hasconfig:")
        .expect("expected a hasconfig rule");

    assert!(
        first_path < first_url,
        "path rules must precede URL rules so the URL wins"
    );
}

#[test]
fn generating_twice_produces_identical_output() {
    let first = generate();
    let second = generate();

    for (a, b) in first.files.iter().zip(second.files.iter()) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.contents, b.contents, "sync is not deterministic");
    }
}

#[test]
fn every_generated_file_says_it_is_generated() {
    // These land next to hand-written config. Anyone opening one should learn
    // immediately that editing it is pointless.
    let plan = generate();

    for f in &plan.files {
        assert!(
            f.contents.contains("generated by gitwho"),
            "{} has no generated-file header",
            f.path.display()
        );
    }
}

/// Ask real git whether the generated rules actually select the right
/// identity. Asserting on the generated text only proves we wrote what we
/// meant to; this proves git agrees.
#[test]
fn generated_rules_match_a_real_scp_remote_with_a_non_git_user() {
    // Digilope's remotes are `gitea@app-gitea.digilope.com:daniel/...`. A
    // `git@` pattern misses them entirely, and the failure is silent: the repo
    // just falls back to the default identity.
    let dir = tempfile::tempdir().unwrap();
    let git_dir = dir.path().join("git");

    let config = Config::parse(
        r#"
        [defaults]
        account = "Personal"
        gitName = "Test Person"

        [[accounts]]
        name = "Personal"
        provider = "github"
        email = "personal@example.com"
        match = ["github.com/Personal/**"]

        [[accounts]]
        name = "Digilope"
        provider = "gitea"
        email = "digilope@example.com"
        match = ["app-gitea.digilope.com/**"]
    "#,
    )
    .unwrap();

    let plan = sync::plan(&config, &git_dir);
    sync::apply(&plan).unwrap();

    let repo = dir.path().join("repo");
    std::fs::create_dir(&repo).unwrap();
    let global = dir.path().join("global.gitconfig");
    std::fs::write(
        &global,
        format!(
            "[include]\n\tpath = {}\n",
            git_dir.join("includes.gitconfig").display()
        ),
    )
    .unwrap();

    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .args(args)
            .current_dir(&repo)
            .env("GIT_CONFIG_GLOBAL", &global)
            .env("GIT_CONFIG_SYSTEM", "/dev/null")
            .output()
            .unwrap()
    };

    git(&["init", "-q", "-b", "main"]);
    git(&[
        "remote",
        "add",
        "origin",
        "gitea@app-gitea.digilope.com:daniel/one-drop-visuals.git",
    ]);

    let email = String::from_utf8_lossy(&git(&["config", "--get", "user.email"]).stdout)
        .trim()
        .to_string();

    assert_eq!(
        email, "digilope@example.com",
        "git did not select the Digilope identity for an scp remote with a non-git user"
    );
}
