use gitwho::config::Config;
use gitwho::sync;

const ACCOUNTS: &str = r#"
    [defaults]
    account = "Personal"
    gitName = "Your Name"

    [[accounts]]
    name = "Personal"
    provider = "github"
    login = "personal"
    email = "me@example.com"
    sshKey = "~/.ssh/id_ed25519_personal"
    match = ["github.com/Personal/**"]
    paths = ["/home/someone/src/personal/"]

    [[accounts]]
    name = "Work"
    provider = "github"
    login = "work"
    email = "me@work.example"
    match = ["github.com/WorkOrg/**"]
"#;

/// The binary path baked into generated config. A parameter rather than
/// `current_exe()` inside `sync`, so a test can assert on an exact string
/// instead of on whatever the test harness happens to be called.
const BINARY: &str = "/home/someone/.local/bin/gitwho";

fn generate() -> sync::Plan {
    let config = Config::parse(ACCOUNTS).unwrap();
    sync::plan(
        &config,
        std::path::Path::new("/home/x/.config/gitwho/git"),
        BINARY,
    )
}

fn file<'a>(plan: &'a sync::Plan, name: &str) -> &'a str {
    plan.files
        .iter()
        .find(|f| f.path.file_name().unwrap() == name)
        .map(|f| f.contents.as_str())
        .unwrap_or_else(|| panic!("no generated file named {name}"))
}

#[test]
fn each_account_gets_an_identity_file() {
    let plan = generate();
    let personal = file(&plan, "Personal.gitconfig");

    assert!(personal.contains("email = me@example.com"));
    assert!(personal.contains("name = Your Name"));
}

#[test]
fn an_account_with_an_ssh_key_pins_it_and_one_without_does_not() {
    let plan = generate();

    assert!(
        file(&plan, "Personal.gitconfig").contains("sshcommand"),
        "an account declaring a key should pin it"
    );
    assert!(
        !file(&plan, "Work.gitconfig").contains("sshcommand"),
        "an account with no key must not inherit someone else's"
    );
}

/// `hasconfig:remote.*.url:` matches the literal remote string, so one account
/// pattern has to become every URL spelling of it -- otherwise an ssh clone of
/// a matched org silently misses.
#[test]
fn a_pattern_becomes_every_url_form_git_might_see() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    for expected in [
        "hasconfig:remote.*.url:https://github.com/Personal/**",
        "hasconfig:remote.*.url:*@github.com:Personal/**",
        "hasconfig:remote.*.url:ssh://*@github.com/Personal/**",
    ] {
        assert!(
            includes.contains(expected),
            "missing URL form {expected}; got:\n{includes}"
        );
    }
}

#[test]
fn declared_paths_become_gitdir_rules_for_repos_with_no_remote() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    assert!(
        includes.contains("gitdir:/home/someone/src/personal/"),
        "a declared path should produce a gitdir rule; got:\n{includes}"
    );
}

/// URL rules must come after path rules: last include wins in git, and the
/// remote is the better evidence.
#[test]
fn url_rules_are_applied_after_path_rules() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    let first_path = includes.find("gitdir:").expect("expected a gitdir rule");
    let first_url = includes
        .find("hasconfig:")
        .expect("expected a hasconfig rule");

    assert!(
        first_path < first_url,
        "path rules must precede URL rules so the URL wins"
    );
}

#[test]
fn generating_twice_produces_identical_output() {
    let first = generate();
    let second = generate();

    for (a, b) in first.files.iter().zip(second.files.iter()) {
        assert_eq!(a.path, b.path);
        assert_eq!(a.contents, b.contents, "sync is not deterministic");
    }
}

#[test]
fn every_generated_file_says_it_is_generated() {
    // These land next to hand-written config. Anyone opening one should learn
    // immediately that editing it is pointless.
    let plan = generate();

    for f in &plan.files {
        assert!(
            f.contents.contains("generated by gitwho"),
            "{} has no generated-file header",
            f.path.display()
        );
    }
}

/// Ask real git whether the generated rules actually select the right
/// identity. Asserting on the generated text only proves we wrote what we
/// meant to; this proves git agrees.
#[test]
fn generated_rules_match_a_real_scp_remote_with_a_non_git_user() {
    // SelfHosted's remotes are `gitea@ssh.git.example.net:someone/...`. A
    // `git@` pattern misses them entirely, and the failure is silent: the repo
    // just falls back to the default identity.
    let dir = tempfile::tempdir().unwrap();
    let git_dir = dir.path().join("git");

    let config = Config::parse(
        r#"
        [defaults]
        account = "Personal"
        gitName = "Test Person"

        [[accounts]]
        name = "Personal"
        provider = "github"
        login = "personal"
        email = "personal@example.com"
        match = ["github.com/Personal/**"]

        [[accounts]]
        name = "SelfHosted"
        provider = "gitea"
        login = "selfhosted"
        url = "https://ssh.git.example.net"
        email = "you@example.net"
        match = ["ssh.git.example.net/**"]
    "#,
    )
    .unwrap();

    let plan = sync::plan(&config, &git_dir, BINARY);
    sync::apply(&plan).unwrap();

    let repo = dir.path().join("repo");
    std::fs::create_dir(&repo).unwrap();
    let global = dir.path().join("global.gitconfig");
    std::fs::write(
        &global,
        format!(
            "[include]\n\tpath = {}\n",
            git_dir.join("includes.gitconfig").display()
        ),
    )
    .unwrap();

    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .args(args)
            .current_dir(&repo)
            .env("GIT_CONFIG_GLOBAL", &global)
            .env("GIT_CONFIG_SYSTEM", "/dev/null")
            .output()
            .unwrap()
    };

    git(&["init", "-q", "-b", "main"]);
    git(&[
        "remote",
        "add",
        "origin",
        "gitea@ssh.git.example.net:someone/site.git",
    ]);

    let email = String::from_utf8_lossy(&git(&["config", "--get", "user.email"]).stdout)
        .trim()
        .to_string();

    assert_eq!(
        email, "you@example.net",
        "git did not select the SelfHosted identity for an scp remote with a non-git user"
    );
}

// --- Credential sections -----------------------------------------------------
//
// The hand-written gitconfig block these replace was the most error-prone step
// of the install: three separate details, each of which fails silently.

/// Without `useHttpPath`, git tells the helper `github.com` and nothing more,
/// so every account on that host resolves identically. The empty `helper =` is
/// a reset: without it this appends to a list and whatever ran first still
/// answers.
#[test]
fn a_credential_section_carries_the_reset_the_helper_and_the_http_path() {
    let plan = generate();
    let creds = file(&plan, "credentials.gitconfig");

    let section = creds
        .split("[credential ")
        .find(|s| s.starts_with("\"https://github.com\"]"))
        .expect("expected a section for github.com");

    assert!(
        section.contains("\n\thelper =\n"),
        "the empty reset must come first, or a previously configured helper still answers; got:\n{section}"
    );
    assert!(
        section.contains(&format!("helper = {BINARY} credential")),
        "the helper must name the absolute path of the binary that generated it; got:\n{section}"
    );
    assert!(
        section.contains("useHttpPath = true"),
        "without useHttpPath the org never reaches the helper and every account on the host resolves the same; got:\n{section}"
    );
}

/// Two accounts on one host is the case this whole project exists for. Git
/// takes the last matching section, so emitting the host twice would make the
/// second silently shadow the first -- and both say the same thing anyway,
/// since the helper resolves the account from the path git passes it.
#[test]
fn two_accounts_on_one_host_produce_one_section() {
    let plan = generate();
    let creds = file(&plan, "credentials.gitconfig");

    assert_eq!(
        creds.matches("[credential \"https://github.com\"]").count(),
        1,
        "github.com should appear exactly once; got:\n{creds}"
    );
}

/// The whole point of generating this file is that the user still adds exactly
/// one line to their own gitconfig. If it is not reachable from the file they
/// include, it does nothing.
#[test]
fn the_credential_file_is_reachable_from_the_one_included_file() {
    let plan = generate();
    let includes = file(&plan, "includes.gitconfig");

    assert!(
        includes.contains("credentials.gitconfig"),
        "includes.gitconfig must pull in the credential sections; got:\n{includes}"
    );
}

/// Same reasoning as the identity test above: ask real git which helper it
/// would actually use, rather than trusting that the text we generated means
/// what we think. `--get-urlmatch` is how git itself resolves a url-scoped
/// section, so this exercises the precedence rule the hand-written version got
/// wrong.
#[test]
fn git_resolves_the_generated_credential_section_for_a_real_url() {
    let dir = tempfile::tempdir().unwrap();
    let git_dir = dir.path().join("git");

    let config = Config::parse(ACCOUNTS).unwrap();
    let plan = sync::plan(&config, &git_dir, BINARY);
    sync::apply(&plan).unwrap();

    let global = dir.path().join("global.gitconfig");
    std::fs::write(
        &global,
        format!(
            // A pre-existing general helper, because that is the situation
            // anyone installing this is actually in. It must lose.
            "[credential]\n\thelper = some-other-manager\n[include]\n\tpath = {}\n",
            git_dir.join("includes.gitconfig").display()
        ),
    )
    .unwrap();

    let git = |args: &[&str]| {
        let out = std::process::Command::new("git")
            .args(args)
            .env("GIT_CONFIG_GLOBAL", &global)
            .env("GIT_CONFIG_SYSTEM", "/dev/null")
            .output()
            .unwrap();
        String::from_utf8_lossy(&out.stdout).trim().to_string()
    };

    let helpers = git(&[
        "config",
        "--get-urlmatch",
        "credential.helper",
        "https://github.com/WorkOrg/thing.git",
    ]);
    assert_eq!(
        helpers,
        format!("{BINARY} credential"),
        "git should resolve a claimed host to gitwho alone -- the reset must have cleared the pre-existing helper"
    );

    assert_eq!(
        git(&[
            "config",
            "--get-urlmatch",
            "credential.useHttpPath",
            "https://github.com/WorkOrg/thing.git",
        ]),
        "true",
        "without useHttpPath the org never reaches the helper"
    );

    // A host nobody claimed must be left exactly as it was.
    assert_eq!(
        git(&[
            "config",
            "--get-urlmatch",
            "credential.helper",
            "https://gitlab.example.com/someone/thing.git",
        ]),
        "some-other-manager",
        "an unclaimed host must keep whatever was already configured"
    );
}
