//! Generating wrapper scripts that route a CLI through `gitfriend exec`.
//!
//! A shim is how a tool that reads environment variables gets covered without
//! wrapping every call site by hand: put the shim directory early on `PATH`,
//! and `gh` means `gitfriend exec -- /real/path/to/gh`.

use std::path::{Path, PathBuf};

#[derive(Debug, thiserror::Error)]
pub enum ShimError {
    #[error("cannot find {name} on PATH to wrap")]
    NotFound { name: String },
    #[error("cannot write shim {path}: {source}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Find the real binary for `name`, ignoring anything inside `shim_dir`.
///
/// Skipping the shim directory is what stops a generated shim from finding
/// itself and recursing forever.
pub fn find_real_binary(name: &str, shim_dir: &Path, path_var: &str) -> Option<PathBuf> {
    let shim_dir = shim_dir.canonicalize().ok();

    std::env::split_paths(path_var)
        .filter(|dir| match (&shim_dir, dir.canonicalize().ok()) {
            (Some(shim), Some(candidate)) => *shim != candidate,
            _ => true,
        })
        .map(|dir| dir.join(name))
        .find(|candidate| candidate.is_file())
}

/// Write a shim for `name` into `shim_dir`.
///
/// The real binary's absolute path is baked in rather than re-resolved at run
/// time: it makes the shim trivially readable, and a stale path is something
/// `doctor` can detect, whereas a recursion loop is not.
pub fn install(name: &str, shim_dir: &Path, path_var: &str) -> Result<PathBuf, ShimError> {
    std::fs::create_dir_all(shim_dir).map_err(|source| ShimError::Write {
        path: shim_dir.to_path_buf(),
        source,
    })?;

    let real = find_real_binary(name, shim_dir, path_var).ok_or_else(|| ShimError::NotFound {
        name: name.to_string(),
    })?;

    let gitfriend = std::env::current_exe().map_err(|source| ShimError::Write {
        path: shim_dir.to_path_buf(),
        source,
    })?;

    let script = format!(
        "#!/bin/sh\n\
         # Generated by gitfriend. Re-run `gitfriend shim install {name}` after\n\
         # the wrapped binary moves.\n\
         exec {} exec -- {} \"$@\"\n",
        shell_quote(&gitfriend.to_string_lossy()),
        shell_quote(&real.to_string_lossy()),
    );

    let path = shim_dir.join(name);
    std::fs::write(&path, script).map_err(|source| ShimError::Write {
        path: path.clone(),
        source,
    })?;
    make_executable(&path)?;

    Ok(path)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

#[cfg(unix)]
fn make_executable(path: &Path) -> Result<(), ShimError> {
    use std::os::unix::fs::PermissionsExt;

    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).map_err(|source| {
        ShimError::Write {
            path: path.to_path_buf(),
            source,
        }
    })
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) -> Result<(), ShimError> {
    Ok(())
}
