//! Generating the git configuration that selects an identity.
//!
//! Everything here is written into gitwho's own directory and nowhere else.
//! Hand-maintained config is never parsed or rewritten -- it only needs a
//! single line added once:
//!
//! ```ini
//! [include]
//!     path = ~/.config/gitwho/git/includes.gitconfig
//! ```
//!
//! That boundary is what makes this safe to re-run: there is no marked region
//! to preserve, no merge to get wrong, and removing gitwho is deleting a
//! directory and one line.

use std::path::{Path, PathBuf};

use crate::config::{Account, Config};

const HEADER: &str = "# This file is generated by gitwho. Edits will be overwritten.\n\
                      # Change accounts.toml and re-run `gitwho sync` instead.\n";

#[derive(Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: PathBuf,
    pub contents: String,
}

#[derive(Debug)]
pub struct Plan {
    pub files: Vec<GeneratedFile>,
}

/// Work out every file that should exist, without touching the disk.
///
/// `gitwho` is the absolute path of this binary, baked into the credential
/// helper lines. It is a parameter rather than a `current_exe()` call in here
/// so the generated text is a pure function of its inputs and a test can assert
/// on an exact string. The same baked-path hazard applies as to
/// [`shim::install`](crate::shim::install): move the binary and re-run.
pub fn plan(config: &Config, dir: &Path, gitwho: &str) -> Plan {
    let mut files = Vec::new();

    for account in &config.accounts {
        files.push(GeneratedFile {
            path: dir.join(format!("{}.gitconfig", account.name)),
            contents: identity_file(config, account),
        });
    }

    files.push(GeneratedFile {
        path: dir.join(CREDENTIALS_FILE),
        contents: credentials_file(config, gitwho),
    });

    files.push(GeneratedFile {
        path: dir.join("includes.gitconfig"),
        contents: includes_file(config, dir),
    });

    Plan { files }
}

const CREDENTIALS_FILE: &str = "credentials.gitconfig";

/// The hosts gitwho serves credentials for, in declaration order, deduplicated.
///
/// Only accounts that declare a `gitCredential` contribute. An account that
/// only ever uses ssh has no token to serve, and claiming its host would mean
/// answering a fill request with nothing -- which reads to git as a failure
/// rather than as "not mine" (R7).
fn served_hosts(config: &Config) -> Vec<&str> {
    let mut hosts: Vec<&str> = Vec::new();

    for account in &config.accounts {
        if account.git_credential.is_none() {
            continue;
        }
        for pattern in &account.match_patterns {
            let host = pattern.split('/').next().unwrap_or(pattern);
            if !host.is_empty() && !hosts.contains(&host) {
                hosts.push(host);
            }
        }
    }

    hosts
}

/// The `[credential]` sections, which used to be transcribed by hand.
///
/// Three details here are load-bearing, and each fails *silently* when it is
/// wrong -- which is the whole reason this is generated rather than documented:
///
/// - **The empty `helper =` is a reset, not a helper.** It clears everything
///   configured before it. Without it this appends to a list, and whatever ran
///   first still answers.
/// - **A url-scoped section overrides the general helper list outright.** So
///   setting only the global `credential.helper` achieves nothing once one of
///   these exists -- and, conversely, these leave other hosts alone.
/// - **`useHttpPath = true` is mandatory for multi-account hosts.** Without it
///   git passes `github.com` and nothing more, so every account on that host
///   resolves identically: a total and silent failure.
fn credentials_file(config: &Config, gitwho: &str) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "#\n\
         # Credential helper wiring, one section per host any account claims.\n\
         # Hosts not listed here are left to whatever you already configured.\n",
    );

    for host in served_hosts(config) {
        out.push_str(&format!("\n[credential \"https://{host}\"]\n"));
        // Empty value first: this is a reset of the helper list, so a
        // previously configured helper cannot answer ahead of gitwho.
        out.push_str("\thelper =\n");
        out.push_str(&format!("\thelper = {gitwho} credential\n"));
        // Without this the helper is told the host and nothing else, so every
        // account on it resolves the same way.
        out.push_str("\tuseHttpPath = true\n");
    }

    out
}

fn identity_file(config: &Config, account: &Account) -> String {
    let name = account
        .git_name
        .as_deref()
        .or(config.defaults.git_name.as_deref())
        .unwrap_or_default();

    let mut out = String::from(HEADER);
    out.push_str(&format!("# Identity for the {} account.\n\n", account.name));
    out.push_str("[user]\n");
    out.push_str(&format!("\tname = {name}\n"));
    out.push_str(&format!("\temail = {}\n", account.email));

    // Only when the account actually has a key. Pinning someone else's, or a
    // default, is how an ssh push ends up authenticating as the wrong person.
    if let Some(key) = &account.ssh_key {
        out.push_str("\n[core]\n");
        out.push_str(&format!("\tsshcommand = ssh -i {key}\n"));
    }

    out
}

fn includes_file(config: &Config, dir: &Path) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "# Include this from your main gitconfig:\n\
         #     [include]\n\
         #         path = <this file>\n\
         #\n\
         # That one line is the whole hookup. Everything else gitwho generates\n\
         # is reached from here, so removing it hands control straight back.\n\n",
    );

    // Unconditional, and first: these are `[credential]` sections rather than
    // `includeIf` rules, so they do not compete with the identity rules below
    // and there is nothing to order them against.
    out.push_str("# Which helper answers for which host.\n");
    out.push_str("[include]\n");
    out.push_str(&format!(
        "\tpath = {}\n\n",
        dir.join(CREDENTIALS_FILE).display()
    ));

    // Path rules first. Git applies includes in order and the last match wins,
    // so putting URL rules afterwards lets the remote -- the better evidence --
    // override a directory guess. Path rules only decide anything for a repo
    // with no remote at all.
    out.push_str("# Directory rules. These decide only for repos with no remote yet;\n");
    out.push_str("# anything with a remote is settled by the URL rules below.\n");
    for account in &config.accounts {
        for prefix in &account.paths {
            out.push_str(&format!("[includeIf \"gitdir:{prefix}\"]\n"));
            out.push_str(&format!(
                "\tpath = {}\n",
                dir.join(format!("{}.gitconfig", account.name)).display()
            ));
        }
    }

    out.push_str("\n# URL rules. Location-independent: these hold for a clone made\n");
    out.push_str("# anywhere and for a worktree in a foreign root.\n");
    for account in &config.accounts {
        for pattern in &account.match_patterns {
            for url in crate::resolve::url_forms(pattern) {
                out.push_str(&format!("[includeIf \"hasconfig:remote.*.url:{url}\"]\n"));
                out.push_str(&format!(
                    "\tpath = {}\n",
                    dir.join(format!("{}.gitconfig", account.name)).display()
                ));
            }
        }
    }

    out
}

/// Write the plan, returning the paths that actually changed.
pub fn apply(plan: &Plan) -> std::io::Result<Vec<PathBuf>> {
    let mut changed = Vec::new();

    for file in &plan.files {
        if let Some(parent) = file.path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Comparing first keeps re-runs quiet and leaves mtimes alone, so
        // "what did sync change?" has an honest answer.
        let current = std::fs::read_to_string(&file.path).ok();
        if current.as_deref() == Some(file.contents.as_str()) {
            continue;
        }
        std::fs::write(&file.path, &file.contents)?;
        changed.push(file.path.clone());
    }

    Ok(changed)
}
