//! Generating the git configuration that selects an identity.
//!
//! Everything here is written into gitwho's own directory and nowhere else.
//! Hand-maintained config is never parsed or rewritten -- it only needs a
//! single line added once:
//!
//! ```ini
//! [include]
//!     path = ~/.config/gitwho/git/includes.gitconfig
//! ```
//!
//! That boundary is what makes this safe to re-run: there is no marked region
//! to preserve, no merge to get wrong, and removing gitwho is deleting a
//! directory and one line.

use std::path::{Path, PathBuf};

use crate::config::{Account, Config};

const HEADER: &str = "# This file is generated by gitwho. Edits will be overwritten.\n\
                      # Change accounts.toml and re-run `gitwho sync` instead.\n";

#[derive(Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: PathBuf,
    pub contents: String,
}

#[derive(Debug)]
pub struct Plan {
    pub files: Vec<GeneratedFile>,
}

/// Work out every file that should exist, without touching the disk.
pub fn plan(config: &Config, dir: &Path) -> Plan {
    let mut files = Vec::new();

    for account in &config.accounts {
        files.push(GeneratedFile {
            path: dir.join(format!("{}.gitconfig", account.name)),
            contents: identity_file(config, account),
        });
    }

    files.push(GeneratedFile {
        path: dir.join("includes.gitconfig"),
        contents: includes_file(config, dir),
    });

    Plan { files }
}

fn identity_file(config: &Config, account: &Account) -> String {
    let name = account
        .git_name
        .as_deref()
        .or(config.defaults.git_name.as_deref())
        .unwrap_or_default();

    let mut out = String::from(HEADER);
    out.push_str(&format!("# Identity for the {} account.\n\n", account.name));
    out.push_str("[user]\n");
    out.push_str(&format!("\tname = {name}\n"));
    out.push_str(&format!("\temail = {}\n", account.email));

    // Only when the account actually has a key. Pinning someone else's, or a
    // default, is how an ssh push ends up authenticating as the wrong person.
    if let Some(key) = &account.ssh_key {
        out.push_str("\n[core]\n");
        out.push_str(&format!("\tsshcommand = ssh -i {key}\n"));
    }

    out
}

fn includes_file(config: &Config, dir: &Path) -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "# Include this from your main gitconfig:\n\
         #     [include]\n\
         #         path = <this file>\n\n",
    );

    // Path rules first. Git applies includes in order and the last match wins,
    // so putting URL rules afterwards lets the remote -- the better evidence --
    // override a directory guess. Path rules only decide anything for a repo
    // with no remote at all.
    out.push_str("# Directory rules. These decide only for repos with no remote yet;\n");
    out.push_str("# anything with a remote is settled by the URL rules below.\n");
    for account in &config.accounts {
        for prefix in &account.paths {
            out.push_str(&format!("[includeIf \"gitdir:{prefix}\"]\n"));
            out.push_str(&format!(
                "\tpath = {}\n",
                dir.join(format!("{}.gitconfig", account.name)).display()
            ));
        }
    }

    out.push_str("\n# URL rules. Location-independent: these hold for a clone made\n");
    out.push_str("# anywhere and for a worktree in a foreign root.\n");
    for account in &config.accounts {
        for pattern in &account.match_patterns {
            for url in url_forms(pattern) {
                out.push_str(&format!("[includeIf \"hasconfig:remote.*.url:{url}\"]\n"));
                out.push_str(&format!(
                    "\tpath = {}\n",
                    dir.join(format!("{}.gitconfig", account.name)).display()
                ));
            }
        }
    }

    out
}

/// Every way git might spell a remote matching `host/path`.
///
/// `hasconfig:remote.*.url:` compares against the literal remote string, so a
/// single `host/org/**` pattern has to be expanded. Missing a form is silent:
/// an ssh clone of a matched org would simply not match, and fall back to the
/// default identity.
fn url_forms(pattern: &str) -> Vec<String> {
    let Some((host, rest)) = pattern.split_once('/') else {
        return vec![pattern.to_string()];
    };

    vec![
        format!("https://{host}/{rest}"),
        // scp-style. The user is wildcarded because it is not always `git`:
        // a Gitea host serves `gitea@host:org/repo.git`, and a literal `git@`
        // pattern misses it silently -- the repo simply falls back to the
        // default identity. Verified against git 2.50.1 that `*@`
        // matches while a bare `*host*` does not, since `*` will not cross a
        // path separator.
        format!("*@{host}:{rest}"),
        // Both spellings, because `**` only spans separators when it follows
        // one. Directly after the `:` it degrades to a single `*`, so a
        // host-wide pattern (`host/**`) needs the `:*/` form to reach
        // `org/repo`. Measured, not assumed: `host:**` does not match while
        // `host:*/**` does. The redundant one is harmless for patterns that
        // already name an org.
        format!("*@{host}:*/{rest}"),
        format!("ssh://*@{host}/{rest}"),
        // ssh URLs need not carry a user at all.
        format!("ssh://{host}/{rest}"),
    ]
}

/// Write the plan, returning the paths that actually changed.
pub fn apply(plan: &Plan) -> std::io::Result<Vec<PathBuf>> {
    let mut changed = Vec::new();

    for file in &plan.files {
        if let Some(parent) = file.path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Comparing first keeps re-runs quiet and leaves mtimes alone, so
        // "what did sync change?" has an honest answer.
        let current = std::fs::read_to_string(&file.path).ok();
        if current.as_deref() == Some(file.contents.as_str()) {
            continue;
        }
        std::fs::write(&file.path, &file.contents)?;
        changed.push(file.path.clone());
    }

    Ok(changed)
}
